# Placeholder hardware configuration for the example host / flake checks.
# On a real machine, replace with the file generated by:
#   nixos-generate-config
{ lib, ... }:

{
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
