font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0

window_padding_width 10
placement_strategy center
hide_window_decorations yes
confirm_os_window_close 0

background_opacity 0.75
dynamic_background_opacity yes

# Pro Dark (Catppuccin Mocha) Palette
foreground           #CDD6F4
background           #1E1E2E
selection_foreground #1E1E2E
selection_background #F5E0DC

# Black
color0 #45475A
color8 #585B70

# Red
color1 #F38BA8
color9 #F38BA8

# Green
color2 #A6E3A1
color10 #A6E3A1

# Yellow
color3 #F9E2AF
color11 #F9E2AF

# Blue
color4 #89B4FA
color12 #89B4FA

# Magenta / Mauve
color5 #CBA6F7
color13 #CBA6F7

# Cyan
color6 #94E2D5
color14 #94E2D5

# White
color7 #BAC2DE
color15 #A6ADC8